### ISSUE TITLE
ESO 9.2.5 changed ZO_LeaderboardRaidProvider to ZO_LeaderboardRaidProvider

### ISSUE THREAD

**Issue by allquixotic** [ESOUIMods/NoThankYou#1]
In line 582 of NoThankYou.lua

Update ZO_LeaderboardRaidProvider to ZO_LeaderboardScoreProvider

This fixes a crash, but then I have some really weird behavior where my FPS tanks, and the MOTD notifications still display. I think something is additionally broken, so don't just update this and call it a day.

I had to comment out HookRaidNotifications() call on line 2115 to get NoThankYou to work happily on 9.2.5.

**Comment by Sharlikran** [comment]
I am not the author and I do not maintain or have access to upload a new version.
